name = "LatticeUtilities"
uuid = "33fcf0eb-3ae3-43db-bfbc-1d92a3639bd1"
authors = ["Benjamin Cohen-Stead <benwcs@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = ">=1.7.0"
